from KnowledgeBase import *

# Tạo đối tượng WumpusKB
a = WumpusKB()

# Thêm các mệnh đề vào Knowledge Base
a.add_clause(Not(symbols('W31')))
a.add_clause(Not(symbols('B11')))
a.add_clause(Not(symbols('W_H31')))
a.add_clause(Not(symbols('C42')))
a.add_clause(Not(symbols('W44')))
a.add_clause(Not(symbols('W12')))
a.add_clause(Not(symbols('P21')))
a.add_clause(Not(symbols('C11')))
a.add_clause(Not(symbols('P32')))
a.add_clause(Not(symbols('P22')))

# Mệnh đề với Or
P33, P42, P44 = symbols('P33 P42 P44')
a.add_clause(Or(P33, P42, P44))

a.add_clause(Not(symbols('C43')))
a.add_clause(Not(symbols('W11')))
a.add_clause(Not(symbols('P_G11')))
a.add_clause(Not(symbols('W_H11')))
a.add_clause(Not(symbols('H_P32')))
a.add_clause(symbols('B43'))
a.add_clause(Not(symbols('C41')))
a.add_clause(Not(symbols('W_H42')))
a.add_clause(Not(symbols('W33')))
a.add_clause(Not(symbols('P_G44')))
# a.add_clause(Not(symbols('H_P44')))
a.add_clause(Not(symbols('S41')))
a.add_clause(Not(symbols('P_G41')))
a.add_clause(Not(symbols('G_L41')))
a.add_clause(Not(symbols('G_L43')))
a.add_clause(Not(symbols('B42')))
# a.add_clause(Not(symbols('H_P22')))
a.add_clause(Not(symbols('P31')))
a.add_clause(Not(symbols('W32')))
a.add_clause(Not(symbols('P42')))
a.add_clause(Not(symbols('C31')))
a.add_clause(Not(symbols('P_G31')))
# a.add_clause(Not(symbols('H_P33')))
a.add_clause(Not(symbols('G_L11')))
a.add_clause(Not(symbols('G_L42')))
a.add_clause(Not(symbols('C21')))
a.add_clause(Not(symbols('G_L21')))
a.add_clause(Not(symbols('W41')))
a.add_clause(Not(symbols('H_P41')))
a.add_clause(Not(symbols('S42')))
a.add_clause(Not(symbols('W21')))
a.add_clause(Not(symbols('P41')))
a.add_clause(Not(symbols('P_G42')))
a.add_clause(Not(symbols('P12')))
# a.add_clause(Not(symbols('H_P11')))
a.add_clause(Not(symbols('P_G22')))
a.add_clause(Not(symbols('W_H43')))

# Mệnh đề với Or
H_P21, H_P32, H_P41 = symbols('H_P21 H_P32 H_P41')
a.add_clause(Or(H_P21, H_P32, H_P41))

a.add_clause(Not(symbols('B31')))
a.add_clause(Not(symbols('B21')))
a.add_clause(Not(symbols('B41')))
a.add_clause(Not(symbols('W43')))
a.add_clause(Not(symbols('W42')))
a.add_clause(Not(symbols('P11')))
a.add_clause(Not(symbols('P_G21')))
a.add_clause(Not(symbols('P43')))
# a.add_clause(Not(symbols('H_P43')))
a.add_clause(Not(symbols('S21')))
a.add_clause(Not(symbols('P_G12')))
a.add_clause(Not(symbols('P_G32')))
# a.add_clause(Not(symbols('H_P31')))
a.add_clause(symbols('G_L31'))
a.add_clause(Not(symbols('P_G43')))
a.add_clause(Not(symbols('S43')))
a.add_clause(Not(symbols('S31')))
a.add_clause(Not(symbols('H_P21')))
a.add_clause(Not(symbols('W_H21')))
# a.add_clause(Not(symbols('H_P42')))
a.add_clause(Not(symbols('S11')))
# a.add_clause(Not(symbols('H_P12')))
a.add_clause(Not(symbols('P_G33')))
a.add_clause(Not(symbols('W22')))
a.add_clause(Not(symbols('W_H41')))

# Inference
print(a.infer(symbols('P44')))


